<?php
/**
 * @var ScopeTooltip $block
 * @var Escaper $escaper
 */

use LFuser\CategoryContentManagement\Block\Adminhtml\Category\Attribute\ScopeTooltip;
use Magento\Framework\Escaper;

?>
<script type="text/x-magento-init">
    {
        "*": {
            "LFuser_CategoryContentManagement/js/category/attribute/scope-tooltip": {
                "submitUrl": "<?= $escaper->escapeUrl($block->getSubmitUrl()) ?>",
                "validFields": <?= $block->getAttributeConfig() ?>
            }
        }
    }
</script>