<?php
/**
 * @var MassAssignButton $block
 * @var Escaper $escaper
 */

use LFuser\CategoryContentManagement\Block\Adminhtml\Category\Product\MassAssignButton;
use Magento\Framework\Escaper;

?>
<button type="button" class="action-default scalable action-secondary" id="category-mass-assign-button"><?= __('Mass Assign') ?></button>
<div id="mass-assign-modal-wrapper" style="display: none">
    <div class="admin__field">
        <label class="admin__field-label" for="sorting-mode">
            <span><?= $block->escapeHtml(__('Sorting Mode')) ?></span>
        </label>
        <select name="sorting_mode" id="sorting-mode" class="admin__control-select">
            <option value="after"><?= __('After') ?></option>
            <option value="before"><?= __('Before') ?></option>
        </select>
    </div>
    <div class="admin__field">
        <label class="admin__field-label" for="assign-products">
            <span><?= $block->escapeHtml(__('Enter SKUs below, one per line')) ?></span>
        </label>
        <div class="admin__field-control">
            <textarea name="assign_products"
                      id="assign-products"
                      class="admin__control-textarea mass-assign-textarea"
                      cols="64"
                      rows="16"></textarea>
        </div>
    </div>
</div>
<script type="text/x-magento-init">
    {
        "#category-mass-assign-button": {
            "LFuser_CategoryContentManagement/js/category/product/mass-assign-button": {
                "submitUrl": "<?= $escaper->escapeUrl($block->getSubmitUrl()) ?>",
                "modalWrapper": "#mass-assign-modal-wrapper",
                "skusContainer": "#assign-products"
            }
        }
    }
</script>
