<?php
/**
 * @var TruncateButton $block
 * @var Escaper $escaper
 */

use LFuser\CategoryContentManagement\Block\Adminhtml\Category\Product\TruncateButton;
use Magento\Framework\Escaper;

?>
<button type="button" class="action-default scalable action-secondary" id="category-truncate-button"><?= __('Truncate') ?></button>
<script type="text/x-magento-init">
    {
        "#category-truncate-button": {
            "LFuser_CategoryContentManagement/js/category/product/truncate-button": {
                "submitUrl": "<?= $escaper->escapeUrl($block->getSubmitUrl()) ?>"
            }
        }
    }
</script>
